# Generated by Django 2.2.4 on 2020-01-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-created']},
        ),
    ]
